import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/General/Header";
import Footer from "@/components/General/Footer";
import StudioGuard from "@/components/General/StudioGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} mt-14 ${geistMono.variable} antialiased`}
      >
        <StudioGuard header={<Header />} footer={<Footer />}>
          {children}
        </StudioGuard>
      </body>
    </html>
  );
}
