import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/General/Header";
import Footer from "@/components/General/Footer";
import StudioGuard from "@/components/General/StudioGuard";
import { QuoteRequestProvider } from "@/components/General/QuoteRequestContext";
import QuoteRequestOverlay from "@/components/General/QuoteRequestOverlay";

const ceraPro = localFont({
  src: [
    {
      path: "../public/cera-pro/Cera-Pro-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/cera-pro/Cera-Pro-Medium.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-cera-pro",
});

const ceraStencil = localFont({
  src: [
    {
      path: "../public/cera-stencil/Cera-Stencil-Regular-Demo.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/cera-stencil/Cera-Stencil-Bold-Demo.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-cera-stencil",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ceraPro.variable} ${ceraStencil.variable}`}>
      <body className={`${ceraPro.className} mt-14 antialiased`}>
        <QuoteRequestProvider>
          <StudioGuard header={<Header />} footer={<Footer />}>
            {children}
          </StudioGuard>
          <QuoteRequestOverlay />
        </QuoteRequestProvider>
      </body>
    </html>
  );
}
